/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simapel;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class Layanan extends javax.swing.JFrame {
private void tampilkanPengaduan() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Isi Pengaduan");
    model.addColumn("Waktu Pengaduan");

    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/simapel", "root", "");
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT * FROM pengaduan ORDER BY waktu_pengaduan DESC");

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_pengaduan"),
                rs.getString("isi_pengaduan"),
                rs.getTimestamp("waktu_pengaduan")
            });
        }

        tblPengaduan.setModel(model);
    } catch (Exception e) {
        e.printStackTrace();
    }
}
private void tampilkanPermohonan() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Layanan");
    model.addColumn("NIK");
    model.addColumn("Nama");
    model.addColumn("TTL");
    model.addColumn("Alamat");
    model.addColumn("Jenis Kelamin");
    model.addColumn("Gol Darah");
    model.addColumn("RT/RW");
    model.addColumn("Desa");
    model.addColumn("Kecamatan");
    model.addColumn("Agama");
    model.addColumn("Pekerjaan");
    model.addColumn("Status");
    model.addColumn("Waktu");

    try {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/simapel", "root", "");
    Statement stmt = conn.createStatement();
    ResultSet rs = stmt.executeQuery(
        "SELECT * FROM permohonan WHERE status_validasi_admin = 'menunggu' OR status_validasi_admin = 'on proses' ORDER BY waktu_pengajuan DESC"
    );
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_permohonan"),
                rs.getString("layanan"),
                rs.getString("nik"),
                rs.getString("nama"),
                rs.getString("ttl"),
                rs.getString("alamat"),
                rs.getString("jenis_kelamin"),
                rs.getString("gol_darah"),
                rs.getString("rt_rw"),
                rs.getString("kel_desa"),
                rs.getString("kecamatan"),
                rs.getString("agama"),
                rs.getString("pekerjaan"),
                rs.getString("status_validasi_admin"),
                rs.getTimestamp("waktu_pengajuan")
            });
        }

        tblPermohonan.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data permohonan: " + e.getMessage());
    }
}



    public Layanan() {
        initComponents();
        lblWelcome.setText("Selamat Bertugas, " + Session.get_nama() + "!");
        tampilkanPengaduan();
        tampilkanPermohonan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPermohonan = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPengaduan = new javax.swing.JTable();
        btnTolak = new javax.swing.JButton();
        btnSetujui = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jmenuRefresh = new javax.swing.JMenuItem();
        Keluar = new javax.swing.JMenuItem();
        jmenuLaporan = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 116, 51));

        jPanel2.setBackground(new java.awt.Color(164, 180, 101));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SISTEM INFORMASI MANAJEMEN PELAYANAN PUBLIK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(353, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(410, 410, 410))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Selamat Bertugas, ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PERMOHONAN MASUK");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PENGADUAN MASUK");

        tblPermohonan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPermohonan);

        tblPengaduan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblPengaduan);

        btnTolak.setBackground(new java.awt.Color(164, 180, 101));
        btnTolak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTolak.setForeground(new java.awt.Color(255, 255, 255));
        btnTolak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/tolak.png"))); // NOI18N
        btnTolak.setText("TOLAK");
        btnTolak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTolakActionPerformed(evt);
            }
        });

        btnSetujui.setBackground(new java.awt.Color(164, 180, 101));
        btnSetujui.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSetujui.setForeground(new java.awt.Color(255, 255, 255));
        btnSetujui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/setuju.png"))); // NOI18N
        btnSetujui.setText("SETUJUI");
        btnSetujui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetujuiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1111, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTolak)
                        .addGap(36, 36, 36)
                        .addComponent(btnSetujui)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSetujui)
                    .addComponent(btnTolak))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jMenu3.setText("Beranda");

        jmenuRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/refresh.png"))); // NOI18N
        jmenuRefresh.setText("Refresh");
        jmenuRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuRefreshActionPerformed(evt);
            }
        });
        jMenu3.add(jmenuRefresh);

        Keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/exit.png"))); // NOI18N
        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        jMenu3.add(Keluar);

        jMenuBar2.add(jMenu3);

        jmenuLaporan.setText("Layanan");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file.png"))); // NOI18N
        jMenuItem3.setText("Laporan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmenuLaporan.add(jMenuItem3);

        jMenuBar2.add(jmenuLaporan);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetujuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetujuiActionPerformed
       btnSetujui.addActionListener(e -> {
    int row = tblPermohonan.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(null, "Pilih data yang akan disetujui!");
        return;
    }

    String id = tblPermohonan.getValueAt(row, 0).toString();

    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/simapel", "root", "");
        String sql = "UPDATE permohonan SET status_validasi_admin='on proses' WHERE id_permohonan=?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, id);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Permohonan telah disetujui dan dikirim ke pimpinan.");
        tampilkanPermohonan(); // refresh tabel admin
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Gagal menyetujui: " + ex.getMessage());
    }
});

    }//GEN-LAST:event_btnSetujuiActionPerformed

    private void btnTolakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTolakActionPerformed
       btnTolak.addActionListener(e -> {
    int row = tblPermohonan.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(null, "Pilih data yang akan ditolak!");
        return;
    }

    String id = tblPermohonan.getValueAt(row, 0).toString();

    // Input alasan penolakan
    String alasan = JOptionPane.showInputDialog(null, "Masukkan alasan penolakan:", "Alasan Penolakan", JOptionPane.QUESTION_MESSAGE);
    
    if (alasan == null || alasan.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Penolakan dibatalkan. Alasan harus diisi.");
        return;
    }

    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/simapel", "root", "");
        String sql = "UPDATE permohonan SET status_validasi_admin='ditolak', alasan_penolakan=? WHERE id_permohonan=?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, alasan);
        pst.setString(2, id);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Permohonan ditolak.\nAlasan: " + alasan);
        tampilkanPermohonan(); // Refresh tabel
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Gagal menolak: " + ex.getMessage());
    }
});


    }//GEN-LAST:event_btnTolakActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
     Login newWin = new Login();
        newWin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    private void jmenuRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuRefreshActionPerformed
    getPengaduan();
    getPermohonan();
    }//GEN-LAST:event_jmenuRefreshActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Laporanadm newWin = new Laporanadm();
        newWin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Layanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Keluar;
    private javax.swing.JButton btnSetujui;
    private javax.swing.JButton btnTolak;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenu jmenuLaporan;
    private javax.swing.JMenuItem jmenuRefresh;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblPengaduan;
    private javax.swing.JTable tblPermohonan;
    // End of variables declaration//GEN-END:variables
private void getPermohonan() {
    DefaultTableModel model = (DefaultTableModel) tblPermohonan.getModel();
    model.setRowCount(0); // hapus data lama

    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/simapel", "root", "");
        // Ambil hanya yang statusnya menunggu atau on proses
        String sql = "SELECT * FROM permohonan WHERE status_validasi_admin IN ('menunggu', 'on proses')";
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            Object[] row = {
                rs.getInt("id_permohonan"),
                rs.getString("layanan"),
                rs.getString("nik"),
                rs.getString("nama"),
                rs.getString("ttl"),
                rs.getString("alamat"),
                rs.getString("jenis_kelamin"),
                rs.getString("gol_darah"),
                rs.getString("rt_rw"),
                rs.getString("kel_desa"),
                rs.getString("kecamatan"),
                rs.getString("agama"),
                rs.getString("pekerjaan"),
                rs.getString("status_validasi_admin"),
                rs.getString("waktu_pengajuan")
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
    }
}
private void getPengaduan() {
    DefaultTableModel model = (DefaultTableModel) tblPengaduan.getModel();
    model.setRowCount(0); // Bersihkan isi tabel sebelum load ulang

    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/simapel", "root", "");
        String sql = "SELECT * FROM pengaduan ORDER BY waktu_pengaduan DESC";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sql);

        while (rs.next()) {
            Object[] row = {
                rs.getInt("id_pengaduan"),
                rs.getString("isi_pengaduan"),
                rs.getTimestamp("waktu_pengaduan")
            };
            model.addRow(row);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data pengaduan: " + e.getMessage());
    }
}
}

